# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lavague_ai_tooling',
                'doc_host': 'https://lavague-ai.github.io',
                'git_url': 'https://github.com/lavague-ai/lavague_ai_tooling',
                'lib_path': 'lavague_ai_tooling'},
  'syms': {'lavague_ai_tooling.core': {'lavague_ai_tooling.core.foo': ('core.html#foo', 'lavague_ai_tooling/core.py')}}}
